version: "3.7"

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    networks:
      - database
      - web
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mariadb:
    image: mariadb:latest
    networks:
      - database
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - database
    environment:
      - PMA_HOST=mariadb
      - VIRTUAL_HOST=sql.local

  # adminer:
  #   image: adminer:latest
  #   networks:
  #     - database
  #   environment:
  #     - ADMINER_DESIGN=nette
  #     - ADMINER_PLUGINS=tables-filter tinymce
  #     - ADMINER_DEFAULT_SERVER=mariadb
  #     - VIRTUAL_HOST=sql.local

  php:
    build:
      context: "./docker/php"
    networks:
      - database
      - web
    volumes:
      - "./public:/var/www/html/"
      - "./src:/var/www/src"
    environment:
      - VIRTUAL_HOST=dev.local

networks:
  database:
  web:
